
title: FROSTT
description: The Formidable Repository of Open Sparse Tensors and Tools
baseurl: "" # the subpath of your site, e.g. /blog
url: "/" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: jekyll-theme-slate

exclude:
  - Gemfile
  - Gemfile.lock

collections:
  tensors:
    output: true
    permalink: /tensors/:path/

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "tensors"
    values:
      layout: "tensor_layout"
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /news/:title.html
      layout: "posts"
      comments: false
      social-share: false

include: ["_pages"]

navbar_pages:
  Main: "/"
  News: "/news/"
  Tensors: "/tensors/"
  Tools: "https://github.com/frostt-tensor"
  Contribute: "/contribute/"

show_downloads: false
google_analytics: UA-90336800-1

datahost_base: 'https://s3.us-east-2.amazonaws.com/frostt/frostt_data'

